src/OnboardingContext.tsx
The call to local storage was not being awaited, so always returning true. This adds an await to that async call.
=> Add an await to the call to StorageUtils.getStoreData for Onboarding

src/More/ENDebugMenu.tsx
We'd like to prevent testers from manipulating data and producing confusing behavior from the app
This commit hides debug menu items that manipulate local data or make calls to the GAEN server. It leaves in place only the most necessary buttons that are useful in keeping track of local vs server state.
=> Hide Problematic Debug Menu Items 

.gitignore, bin/fetch_ha_env.sh, bin/fetch_ha_env_github.sh
Why:
We would like to fetch the ha specific google service info.plist in the
fetch ha script to automate the build process for various HAs.
=> Fetch info.plist in fetch_ha_env script

src/OnboardingContext.tsx, src/locales/languages.ts, src/utils/storage.ts
The current getStoreData and setSetStoreData utilities are very generic
so that they can be used for all data types. Since we recently updated the type
annotations of these functions to return a union type instead of `any` (#4),
we had to do some type gymnastics to make the type signatures align for
more specific use cases, such as storing boolean, string, or null
values.
This commit:
Updates the getStoreData and setStoreData functions to have less
responsibility and not be exported from the utils file in favor of more
specific getters and setters. This has the benefit of being more
explicit about what types are returned from this function, how those
type are encoded, and removes the possibility of storing arbitrary data.
It also consolidates the constants used as async storage keys into …
=> Update storage utility helpers

src/utils/dateTime.ts
As of iOS 13.6, exposure duration values are rounded to the nearest minute:
https://developer.apple.com/documentation/exposurenotification/enexposureinfo/3583714-duration
This commit adjust the exposure duration display logic to accommodate the iOS 13.6 change.
=> Adjust Exposure Duration Text to Accommodate iOS 13.6 Changes

src/AffectedUserFlow/index.tsx, src/navigation/ExposureHistoryStack.tsx, src/navigation/MoreStack.tsx, src/navigation/OnboardingStack.tsx, src/navigation/SelfAssessmentStack.tsx, src/navigation/index.ts
Why:
As a user just downloading the app, I want to be able to select my
preferred language.
This commit:
Fixes a bug where the LanguageSelection screen was removed from the
stack navigator in the OnboardingStack.
Co-Authored-By: Alejandro Dustet <alejandro@thoughtbot.com>
- Download a fresh version of the app
- You should be able to switch languages from the welcome screen.
=> Fix navigation error when selecting a language

ios/AppDelegate.m, ios/BT/ExposureManager.swift, ios/Podfile.lock, src/PermissionsContext.tsx
Why:
We currently have a bug in which the app will not register if it lost
exposure notification permissions if is backgrounded. So we get into a
state where the app says it has permissions when it does not.
This commit:
Add logic to eamit an event of the current status when the app will be
foregrounded and fixes a bug in the event data structure.
Co-Authored-By: johnschoeman <johnschoeman1617@gmail.com>
=> Broadcast enabled status on entering foreground

.github/workflows/build.yml, README.md, android/Gemfile, android/Gemfile.lock, bin/dev_setup.sh
Why:
We would like the dev setup script to automatically copy .env and
.env.bt if the root directory doesnt already have those files. Also we
would like for android and github actions to be using the most recent
version of ruby, 2.7.1
=> Update dev setup script for env and ruby

README.md, bin/fetch_ha_env.sh, bin/set_display_names.sh, bin/set_ha.sh
Why:
----
Each HA will have a unique display name they want shown on the application that gets released to the final user. We need a way to update this properties before cutting a production build
This Commit:
----
- Add a script that uses the libraries `PlistBuddy` and `xmllint` to edit the `Info.plist` for the iOS application and the `strings.xml` for the android application
How to test:
----
- After executing the `fetch_ha_env` script run `./set_display_name.sh` and verify that the names have been updated for both applications.
=> Add script to update display names before release

index.js
Why:
A previous commit removed unused things, but not all so the build step
was broken.
This commit:
Fully removes reactotron.
=> Fix build regressions

.github/workflows/test.yml, ios/Gemfile, ios/Gemfile.lock
Why:
----
The ruby versions for our ios project and the ruby version we are using
for running scripts differ from each other, this causes some
miss-matching on environments and headaches for maintainability.
This Commit:
----
- Update ruby version used on ios project
- Fix same ruby version for our github workflows
=> Update ruby version to use a uniform one

ios/COVIDSafePaths/Base.lproj/LaunchScreen.xib
Update the splash screen image in Xcode to match the updated and approved mockups.
https://trello.com/c/l201ai4o
1. Run a fresh install of the app locally.
2. Ensure the splash screen matches the attached screenshot.
Co-authored-by: tparesi <tparesi@gmail.com>
=> Update splash screen image

src/SelfAssessment/AssessmentOption.spec.tsx, src/SelfAssessment/AssessmentOption.tsx, src/SelfAssessment/AssessmentQuestion.js, src/SelfAssessment/Option.tsx
Why:
----
We would like to have all of our files using typescript.
This Commit:
----
- Convert the AssessmentOption file to TypeScript
Reviewers:
----
This is a major effort around converting the files into TypeScript, this is one commit of many, we are focusing first on having an integrated type system and then we can tackle the behavior of these components.
=> Convert AssessmentOption to TypeScript

src/ExposureHistory/ExposureDatumDetail.tsx, src/navigation/MainNavigator.tsx
Why:
----
When we render the navigators, the logic gate is being run against a variable that can be assigned as a string if both environment variables are present. We need to treat it as a boolean check to avoid rendering errors on the Navigator component.
This Commit:
----
- Casts environment variables check to determine whether to display the self assessment as boolean
=> Fix behavior leaving a string instead of a boolean

src/SelfAssessment/EmergencyAssessment.js, src/locales/en.json
Why:
----
The main reason is that we were missing the labels on the buttons for the Self-Assessment flow, but then more reasons appeared.
We have a script that examines the translation keys used throughout the application and updates the ones that are new or unused for uploading and completing the rest of such translations. We would like to use this script to automate the task of finding unused translation keys but we are seeing erroneous output when executed.
The reason for it is that the parser is encountering a `Trans` component that comes directly from the library creators but that the parsers do not recognize. In our particular case we are seeing that a key like:
```
<0></0><1></1>: <0></0><1></1>
```
Is being added when executing `yarn i18next`. There are [issues] documenting …
=> Stop use of component for translations

bin/fetch_ha_env.sh, bin/fetch_ha_env_github.sh
Why:
----
When we pull the scripts without the silent option, the output from the download is included on the response, and it is being copied to the `.env` file.
This Commit:
----
- Add the silent option to the curl script
=> Add silent option to curl on fetch script

example.env.bt, ios/BT/DebugAction.swift, ios/BT/Extensions/Other/ExposureManager+Extensions.swift, ios/BT/bridge/DebugMenuModule.m, ios/Podfile.lock, src/More/ENDebugMenu.tsx, src/More/ENSubmitDebugForm.tsx, src/More/debugAPI.ts, src/gaen/nativeModule.ts, src/locales/en.json, src/navigation/MoreStack.tsx, src/navigation/index.ts, src/styles/typography.ts
Why:
We would like for our users and testers to be able to submit their
exposure history debug logs.
This commit:
Adds a simple form with optional inputs for email and a description with
the exposure notifications diagnostics logs which when submitted will
post to an web api in which we will store the debug info.
Co-Authored-By: Alejandro Dustet <alejandro@thoughtbot.com>
Co-Authored-By: Matt Buckley <matt@nicethings.io>
Co-Authored-By: Ferrumofomega <sam@pathcheck.org>
=> Add submit debug form screen

src/SelfAssessment/Agreement.js, src/SelfAssessment/AssessmentLayout.spec.tsx, src/SelfAssessment/AssessmentLayout.tsx, src/SelfAssessment/AssessmentStart.js, src/SelfAssessment/EmergencyAssessment.js, src/SelfAssessment/endScreens/AssessmentComplete.js, src/SelfAssessment/endScreens/Caregiver.js, src/SelfAssessment/endScreens/Distancing.js, src/SelfAssessment/endScreens/Emergency.js, src/SelfAssessment/endScreens/Isolate.js, src/SelfAssessment/endScreens/Share.js
Why:
----
We would like to have all of our files using typescript.
This Commit:
----
- Convert the SelfAssessment/Info file to TypeScript
- Rename `Info` to `AssessmentLayout` since it reflects more closely what the file is doing
Reviewers:
----
This is a major effort around converting the files into TypeScript, this is one commit of many, we are focusing first on having an integrated type system and then we can tackle the behavior of these components.
=> Convert SelfAssessment/Info to TypeScript

ios/BT/Info.plist
The unnecessary presence of the camera permissions entry in our `Info.plist`  causes a rejection during app review.
This commit removes the problematic entry from the app's `Info.plist`.
=> (iOS) Remove camera permission entry from info.plist

ios/BT/bridge/DebugMenuModule.m, src/More/ENDebugMenu.tsx, src/gaen/nativeModule.ts
We'd like to verify that crashes are getting logged
This commit adds a debug button to force an app crash on iOS
=> (iOS) Add debug button to force app crash.

android/build.gradle
The minimum version supported by GAEN API is 23.
Source: https://developers.google.com/android/exposure-notifications/exposure-notifications-api
=> Bump minSdkVersion to 23

ios/BT/bridge/DebugMenuModule.m, src/More/ENDebugMenu.tsx, src/gaen/nativeModule.ts
We'd like to remove debug menu buttons that will cease to work when the gaen server verifies key submission requests
This commit removes the existing key submission button from the debug menu, and also updates the underlying method for forcing a crash on iOS
=> (iOS) Debug Menu Updates

src/AffectedUserFlow/AffectedUserContext.tsx, src/AffectedUserFlow/CodeInput/CodeInputForm.spec.tsx, src/AffectedUserFlow/CodeInput/CodeInputForm.tsx, src/AffectedUserFlow/CodeInput/CodeInputScreen.spec.tsx, src/AffectedUserFlow/CodeInput/CodeInputScreen.tsx, src/AffectedUserFlow/CodeInput/EnableExposureNotifications.tsx, src/AffectedUserFlow/index.tsx, src/Home/index.tsx, src/Onboarding/EnableExposureNotifications.tsx, src/Onboarding/NotificationPermissions.tsx, src/PermissionsContext.tsx, src/locales/en.json
Why:
Currently, if a user has not enabled exposure notifications for the app
it is possible to try to submit the verification code in the affected
user flow, which will necessarily error as the exposure notification api
must be accessible in order to submit exposure keys.
We would like to make it such that a user cannot submit a verification
code unless the en api is enabled. Additionally, if the user starts the
affected user flow without enabled exposure notifications, they should
be prompted to enable exposure notifications.
This commit:
Adds a conditional to the CodeInputScreen to conditionally render either
the CodeInputForm or an EnableExposureNotifications screen that has a
link to the settings for en notifications.
Co-Authored-By johnschoeman <johnschoeman1617@gmail.com>
---
=> Only allow code submission when en are enabled

ios/Podfile.lock, package.json, src/More/About.spec.tsx, src/More/About.tsx, src/locales/en.json, yarn.lock
Why:
----
When a user navigates to the `About` screen, they should see the correct application name based on the build as-well-as the information of the version and the number of the build.
This Commit:
----
- Install react-native-device-info library
- Display the application name and the version and build from the device information
- Add tests for the about screen
=> Display application name, version on about screen

src/ExposureHistory/ExposureDetail.tsx, src/ExposureHistory/History/ExposureList.spec.tsx, src/ExposureHistory/History/ExposureListItem.tsx, src/exposure.spec.ts, src/exposure.ts, src/locales/en.json
Why:
----
The actual data for an exposure event is not exact on the moment it happened. Showing an exact date, or relative date, is not correct and leads to confusion. The reality is that when we get an exposure history event, this could have happened anytime between 3 days from the occurrence reported.
How:
---
We opted for generating 3 buckets to classify the time range for an exposure event:
- within 3 days
- between 4 and 6 days
- between 7 and 14 days
Any event over 14 days of age will not be reported.
This PR:
----
- Introduces the exposureWindowBucket function to determine the range
where the exposure event falls in.
- Add translations for expressing the window bucket in words
Reviewers:
----
We needed to add a lot of type casting now that the exposure events that will be shown on …
=> Use time range for exposure history timestamp

ios/en.lproj/InfoPlist.strings, ios/en.lproj/Localizable.strings, src/SelfAssessment/endScreens/AssessmentComplete.spec.js, src/locales/en.json, src/locales/pull.sh, src/locales/push.sh
Why:
----
The push and pull actions for lokalise are not working as expected
This Commit:
----
- Remove location permission strings for iOS
- Extract to `src` not `app`
- Do not search under the `gps` flavor of android to upload files
- Update README portion of scripts with new env variables names
- Change some translations that mention location
- Add option to pull script to include just a set of languages
- Removed unused strings on iOS
- Upload translations from the src folder
- Ran push and updated master translations file on lokalise
Caveat:
----
This Commit does not include the result of running and commiting the `pull` script since it brings several files into the `iOS` and `android` projects that might not be necessary. There are more arguments like the languages to include in the …
=> Update pull and push scripts for lokalise

src/ExposureHistory/History/NoExposures.tsx, src/locales/en.json, src/styles/typography.ts
Added a few minor styling changes to the No Exposures screen.
=> Add Small style additions to No Exposures Page

src/ExposureHistory/index.tsx
Why:
The safearea view background color was a bit off.
=> Update safearea view background color on history

src/PermissionsContext.tsx
Check en permission on app state change …
Why:
Currently if the user updates the permission for the app while the app
is backgrounded the application will not receive the onStatusUpdated
event from the native layer, which leads to a situation where the app
shows the incorrect permission status.
This commit:
Adds a subscription to the PermissionsContext using react-natives
AppState api and will check the permission status on every change of the
app state.
Note that we are still finding cases where the checkENPermission()
method is returning ["Authorized", "Enabled"] when we would expect
["Authorized", "Disabled"], which seems to be another bug unrelated to
the backgrounding behavior.
Co-Authored-By: mattthousand <matt@nicethings.io>
Co-Authored-By: amandabeiner <aebeiner@gmail.com>
=> Check en permission on app state change

ios/COVIDSafePaths.xcodeproj/project.pbxproj
We'd like to be able to desymbolicate crashes
This commit adds a script to upload dsyms at build time
=> (iOS) Upload dsyms to Crashlytics at Build time

.github/workflows/lokalise.yml, android/app/src/bt/res/values-es-rPR/strings.xml, android/app/src/bt/res/values-ht-rHT/strings.xml, android/app/src/bt/res/values-ru/strings.xml, android/app/src/bt/res/values/strings.xml, src/locales/pull.sh
Why:
----
The android file structure resulting from executing the script for the localization files was of the form:
`android/app/src/bt/res/values-{LANG_ISO}/android/app/src/bt/res/values-{LANG_ISO}/strings.xml`
This is incorrect, the files should be stored in the structure
`android/app/src/bt/res/values-{LANG-ISO}/strings.xml`
This Commit:
----
- Update arguments for pulling files for the android project and unzipping them
- Execute pull script for android new file structure
=> Fix lokalise pull script for android

ios/BT/API/Model/ExposureConfiguration.swift
We'd like update the `attenuationDurationThresholds` on our exposure configuration. This change is temporary, as we'll ultimately be getting these values from a server
This commit updates our working exposure configuration to match the `attenuationDurationThresholds` values used by the Swiss PT – DP3T App:
https://github.com/DP-3T/dp3t-config-backend-ch/blob/55fbe7493775402804493eced4c8128ac15db9f8/dpppt-config-backend/src/main/java/org/dpppt/switzerland/backend/sdk/config/ws/model/GAENSDKConfig.java#L15
=> Update exposure configuration (iOS)

src/styles/colors.ts
Why: prior to this commit, the primary background color did not contrast
well with white.
This commit: slightly darkens the primary background color so it
contrasts more clearly with white.
=> Update primary background color

src/More/About.tsx, src/More/Licenses.spec.tsx, src/More/Licenses.tsx, src/locales/en.json
Why: prior to this commit, the About and Licenses screens were not styled
appropriately.
=> Clean up About and Licenses styling

android/build.gradle
Fix Google Play Dev console upload warning.
```
Warnings
Your app currently targets API level 28 and must target at least API level 29 to ensure it is built on the latest APIs optimized for security and performance.
From August 2020, new apps must target at least Android 10 (API level 29).
From November 2020, app updates must target Android 10 (API level 29).
Tip: Change your app's target API level. Learn how.
```
=> Bump Target SDK Version

src/AffectedUserFlow/CodeInput/CodeInputForm.spec.tsx, src/AffectedUserFlow/CodeInput/CodeInputForm.tsx, src/AffectedUserFlow/CodeInput/EnableExposureNotifications.spec.tsx, src/AffectedUserFlow/CodeInput/EnableExposureNotifications.tsx, src/AffectedUserFlow/Complete.spec.tsx, src/AffectedUserFlow/Complete.tsx, src/AffectedUserFlow/PublishConsent/PublishConsentForm.spec.tsx, src/AffectedUserFlow/PublishConsent/PublishConsentForm.tsx, src/AffectedUserFlow/PublishConsent/PublishConsentScreen.spec.tsx, src/AffectedUserFlow/Start.spec.tsx
Why:
----
The `AffectedUserFlow` is lacking some test coverage
This Commit:
----
- Add tests for failing branch and content for Publish Consent Form
- Add tests for the publish consent screen
- Add tests for failure branch of certificate request on CodeInput
- Add tests to enable exposure notifications screen
- Add tests for the complete affected user flow screen
- Add tests for the start flow screen of the affected user flow
=> Add tests for AffectedUserFlow

ios/BT/Extensions/Exposure Notifications/ENTemporaryExposureKey+Extensions.swift
We'd like key data from the native layer to encode properly
This commit encodes key data from the native layer as a base64 string
Co-authored by:
John Schoeman <john.schoeman@thoughtbot.com>
Matt Buckley <matt@nicethings.io>
=> Keydata Encoding Update

__mocks__/react-native-simple-crypto.ts, jest/config.js, src/AffectedUserFlow/hmac.spec.ts, src/AffectedUserFlow/hmac.ts
Why:
----
This helper file was not tested and holds a pretty important part of the logic in sending the data to be verified.
This PR:
----
- Remove unnecessary mock of react-native-simple-crypto
- Transform simple crypto for testing
- Add test for hmac calculation method
Reviewers:
----
The method has quite a few mocks since most of the logic goes through calling the simple crypto library for encryption and random values generation purposes.
=> Add test for hmac key calculation helper

android/app/src/bt/java/covidsafepaths/bt/exposurenotifications/storage/RealmSecureStorageBte.kt
We were trying to delete objects in a `RealmResult<ExposureEntity>` but that's not possible since it's a managed object.
Use `copyFromRealm` to get a in-memory copy and edit it
It was throwing an exception and it interrupted the download flow
=> Do not try to edit RealmResults

bin/set_ha.sh
=> Fix typo in env setup script

android/app/src/main/AndroidManifest.xml, android/app/src/main/res/values-ar/strings.xml, android/app/src/main/res/values-da/strings.xml, android/app/src/main/res/values-el/strings.xml, android/app/src/main/res/values-es-rPR/strings.xml, android/app/src/main/res/values-es/strings.xml, android/app/src/main/res/values-ht-rHT/strings.xml, android/app/src/main/res/values-ht/strings.xml, android/app/src/main/res/values-it/strings.xml, android/app/src/main/res/values-ml/strings.xml, android/app/src/main/res/values-nl/strings.xml, android/app/src/main/res/values-pl/strings.xml, android/app/src/main/res/values-pt-rBR/strings.xml, android/app/src/main/res/values-ru/strings.xml, android/app/src/main/res/values-sk/strings.xml, android/app/src/main/res/values-tl/strings.xml, android/app/src/main/res/values/strings.xml, android/settings.gradle, package.json, src/declarations.d.ts, yarn.lock
This library adds a notification channel that is shown to the user but seems to be unused.
I haven't seen any references in the code, are we using it to get notifications from Firebase?
=> Remove react-native-push-notification

.github/workflows/test.yml, example.env.bt, ios/AppDelegate.m, ios/BT/API/APIClient.swift, ios/BT/API/Model/ExposureConfiguration.swift, ios/BT/API/Requests/ExposureConfigurationRequests.swift, ios/BT/ExposureManager.swift, ios/BT/Extensions/Foundation/String+Extensions.swift
We'd like to be able to set the exposure configuration at runtime instead of hardcoding the value
This commit updates `APIClient` to accept a request to fetch the exposure configuration from the server, and executes that request on `init` (`ExposureManager`) and `willEnterForeground`
=> Fetch Exposure Configuration from Server (iOS)

src/AffectedUserFlow/PublishConsent/PublishConsentForm.tsx, src/ExposureHistory/ExposureDetail.tsx
- Fixes the bell icon in the affected user reporting flow so that it matches with the rest of the screens
- Adds alt-text to the small exposure icon on the exposure detail screen
https://trello.com/c/0eMi0AZP
Using an accessibility inspector, check that the exposure icon has the alt text "Possible COVID-19 exposure"
=> Fix icon in report flow and add alt text to exposure

src/More/LanguageSelection.tsx
When trying to choose a language in iOS devices with a top notch the list overlaps with it, I added a SafeAreaView there to prevent this issue
issue:
fix:
=> Fix language list

src/AffectedUserFlow/CodeInput/CodeInputForm.tsx, src/AffectedUserFlow/CodeInput/EnableExposureNotifications.tsx, src/AffectedUserFlow/Complete.tsx, src/AffectedUserFlow/PublishConsent/PublishConsentForm.tsx, src/ExposureHistory/ExposureDetail.spec.tsx, src/ExposureHistory/ExposureDetail.tsx, src/Home/Home.tsx, src/More/Menu.tsx, src/Onboarding/EulaModal.spec.tsx, src/Onboarding/ExplanationScreen.tsx, src/SelfAssessment/AssessmentStart.spec.tsx, src/components/Button.tsx, src/styles/buttons.ts, src/styles/colors.ts, yarn.lock
Why: our button styling is changing based on new visual design
requirements.
This commit:
- Updates our button component styling
- Uses our button component in several more locations in place of
TouchableOpacity
=> Update button component styling

android/app/src/main/java/covidsafepaths/bt/bridge/ExposureNotificationsPackage.java, android/app/src/main/java/covidsafepaths/bt/exposurenotifications/ExposureKeyModule.java, android/app/src/main/java/org/pathcheck/covidsafepaths/exposurenotifications/DeviceInfoModule.java, ios/BT/bridge/DeviceInfoModule.m, ios/COVIDSafePaths.xcodeproj/project.pbxproj, ios/Podfile.lock, package.json, src/More/About.spec.tsx, src/More/About.tsx, src/More/Licenses.spec.tsx, src/More/Licenses.tsx, src/More/useApplicationInfo.spec.tsx, src/More/useApplicationInfo.ts, src/gaen/nativeModule.ts, yarn.lock
Why:
----
The `react-native-device-info` package has security vulnerabilities potentially leaking phone numbers on the android build. We need to display the info provided by this package without the security vulnerabilities.
How:
----
Native modules are added on the android and ios side exposing the build number, version number and the package name to display to users.
This PR:
----
- Remove RNDeviceInfo dependency.
- Implement device info native module (iOS)
- Implement device info native module (Android)
- Add hook to consume application name and version info
=> Remove rn device info dependency

src/Activation/AcceptEula.spec.tsx, src/Activation/AcceptEula.tsx, src/Onboarding/OnboardingScreen.tsx, src/Onboarding/ValueProposition.tsx, src/Onboarding/Welcome.spec.tsx, src/Onboarding/Welcome.tsx, src/assets/svgs/checkboxChecked.ts, src/assets/svgs/checkboxUnchecked.ts, src/assets/svgs/index.ts, src/components/Button.tsx, src/locales/en.json, src/navigation/ActivationStack.tsx, src/navigation/OnboardingStack.tsx, src/navigation/index.ts, src/styles/buttons.ts, src/styles/forms.ts
Why: the design of our Eula acceptance has changed.
This commit:
- Moves the Eula acceptance to the front of the Activation stack
- Updates the design of the Eula acceptance screen
=> Update EulaModal placement and design

src/exposure.ts, src/factories/exposureDatum.tsx, src/factories/rawExposure.tsx, src/gaen/dataConverter.spec.ts, src/gaen/dataConverters.ts
We'd like Android and iOS to be able to use different GAEN api versions and still be able to vend up exposures to the JS layer
This commit removes `totalRiskScore` and `transmissionRiskLevel` from the `RawExposure` interface so that the native layer can vend up objects containing just a date and duration
=> Remove unused properties from RawExposure interface.

android/app/src/main/java/covidsafepaths/bt/exposurenotifications/ExposureNotificationsModule.java, android/app/src/main/java/org/pathcheck/covidsafepaths/exposurenotifications/DeviceInfoModule.java, ios/BT/ExposureManager.swift, ios/BT/bridge/DeviceInfoModule.m, src/gaen/nativeModule.ts
React Native needs a method to check if the bluetooth is enabled or not, this PR exposes its status.
Also expose a method to check if location is enabled on Android (GAEN requires both to work)
=> Expose method to check if bluetooth is enabled

android/app/src/main/java/covidsafepaths/bt/bridge/ExposureNotificationsPackage.java, android/app/src/main/java/covidsafepaths/bt/exposurenotifications/ExposureHistoryModule.java, android/app/src/main/java/covidsafepaths/bt/exposurenotifications/dto/ExposureInformation.java, android/app/src/main/java/covidsafepaths/bt/exposurenotifications/nearby/ProvideDiagnosisKeysWorker.java, android/app/src/main/java/covidsafepaths/bt/exposurenotifications/storage/ExposureNotificationSharedPreferences.java
Implement Android methods to get current exposures and last detection date.
No changes made on the UI / Javascript side.
If you got an exposure notification in the last 14 days you can go to:
- Exposure history (tab in the middle of the screen)
- EN Debug Menu > Show Exposures
If you go to `EN Debug Menu > Detect Exposures Now` it should update the header that says "Updated X minutes ago" (after an app restart)
=> (Android) Implement exposure history methods

android/app/build.gradle
`ReactNativeConfigModule` was trying to read a `BuildConfig` file using the wrong package name.
That's why env variables in React Native were empty.
https://trello.com/c/6rbibcC1/302-env-variables-dont-populate-on-android
=> Expose environment variables to React Native

ios/BT/API/Requests/DiagnosisKeyRequests.swift
Per https://google.github.io/exposure-notifications-server/server_functional_requirements.html, the key submission request should contain random data to obscure the size of the request to network packet sniffers
This commit generates random data with each key submission request to be added to the payload
=> (iOS) Generate random padding data for each key submission 

src/ExposureHistory/ExposureDetail.spec.tsx, src/ExposureHistory/ExposureDetail.tsx, src/ExposureHistory/History/ExposureList.spec.tsx, src/ExposureHistory/History/ExposureListItem.tsx, src/ExposureHistory/History/index.spec.tsx, src/exposure.spec.ts, src/exposure.ts, src/factories/exposureDatum.tsx, src/gaen/dataConverter.spec.ts, src/gaen/dataConverters.ts
Why:
Previously we had the need to build an exposure history that had needed
to represent days without exposures. Since we are now using a list view
to represent a users exposure history these data types are no longer
needed.
This commit:
Refactors the union type of an ExposureDatum to be an interface.
=> Remove unused exposure types

src/More/ENSubmitDebugForm.tsx
Why?
------
The current button styling was white on white, hiding the button.
This Commit
------
Switch out the current TouchableOpacity to use the shared Button component.
[Trello](https://trello.com/c/WGQ247wx/299-button-regression-submit-debug-screen)
=> Fix Debug Form Button

src/AffectedUserFlow/CodeInput/CodeInputForm.tsx
Why?
------
Cancel button is hidden when the keyboard opens and the number pad is not dismissible. The user is stuck without a way to cancel out of this screen without a valid code. Instead of adding a SafeAreaView here, we decided it was okay that the cancel is hidden while a user inputs a code, so long as the user also has the ability to dismiss the keyboard and cancel at any point.
This Commit
------
Add an onSubmitEditing that dismisses the number pad when pressing done.
[Trello](https://trello.com/c/97krmfzq/300-button-regression-submit-verification-code-small-format-screens)
Navigate to More bottom tab.
Click Report Positive Test Result.
Click Start.
If running in simulator, in CodeInputScreen.tsx, set isEnabled to true.
When entering a code, make sure you can dismiss the keyboard.
=> Make number pad dismissible for Verify Code Screen

src/AffectedUserFlow/hmac.spec.ts, src/AffectedUserFlow/hmac.ts
Why:
----
A couple of things jumped up while we were reviewing the docs:
1. We need to encode TEKeys to base64 and sort them prior to encryption 
The [specification] on the HMAC Calculation says:
```
Each key segment contains the following data, period separated:
base64(TEK), rolling period start, rolling period count, transmission risk.
The key segments are sorted lexicographically based on the base64 encoding.
```
2. We need to skip the transmission risk when serializing TEK's if all risks are 0
The hmac calculation includes the transmission risk on each one of the instances. According to the [implementation], there is an alternative HMAC to be computed if all transmission risks are 0.
We are still seeing errors when submitting to the exposures server but these two fixes are necessary. …
=> Fix hmac calculations

android/fastlane/Fastfile, package.json
In order to distribute debug builds to AppCenter:
- Pass APK path to lane `android_alpha_apk`
- Add command `yarn assemble-android-debug` to build a debug APK. We cannot use `assembleDebug` here because it doesn't include all the resources that React Native needs.
=> (Android) Add yarn command to assemble debug builds

android/app/src/main/java/covidsafepaths/bt/exposurenotifications/DebugMenuModule.java, android/app/src/main/java/covidsafepaths/bt/exposurenotifications/ExposureHistoryModule.java, android/app/src/main/java/covidsafepaths/bt/exposurenotifications/ExposureNotificationClientWrapper.java, android/app/src/main/java/covidsafepaths/bt/exposurenotifications/ExposureNotificationsModule.java, android/app/src/main/java/covidsafepaths/bt/exposurenotifications/dto/RNDiagnosisKey.java, android/app/src/main/java/covidsafepaths/bt/exposurenotifications/dto/RNExposureInformation.java, android/app/src/main/java/covidsafepaths/bt/exposurenotifications/storage/RealmSecureStorageBte.kt, android/app/src/main/java/covidsafepaths/bt/exposurenotifications/utils/RequestCodes.java, android/app/src/main/java/covidsafepaths/bt/exposurenotifications/utils/Util.java, android/app/src/main/java/org/pathcheck/covidsafepaths/MainActivity.java
Implement functionality for these debug buttons:
- Submit debug log
- Show local diagnosis keys
- Force App Crash
- Reset Exposures
These buttons cannot be implemented on Android because we are don't store Exposures in our database (we always take that information from the API)
- Simulate Exposure
- Simulate Exposure Detection Error
https://trello.com/c/ij8EtDKQ/305-add-remaining-debug-functionality
- Submit Debug Log -> Should send AppId, Version, VersionName, LastProcessedFileName & LastDetectionProcessDate
- Show local diagnosis keys -> Displays your diagnosis keys in a new screen
- Force App Crash -> Forces a crash in the app
- Reset Exposures -> Wipes the database, you should see the exposure notification again if you tap on "Detect exposures now"
=> (Android) Implement remaning debug methods

android/app/build.gradle
The previous code was looking for a password if there is a `keystore.jks` file (even if it's not used).
I'm adding placeholders for the password properties in order to make debug builds pass.
=> (Android) Allow to build debug if release key passwords are not present

ios/BT/Extensions/Foundation/String+Extensions.swift, ios/BT/Extensions/Other/ExposureManager+Extensions.swift, src/More/ENDebugMenu.tsx
We need a way to simulate an exposure notification "on demand" and demo the corresponding Exposure Summary and Exposure Details screens to guide discussion about the level of configuration jurisdictions would like (per https://trello.com/c/hg1M9jhp/311-feature-flag-to-demo-gaen-exposure-notifications)
This commit updates the "simulate exposure" debug button to show a push as it would appear to a user when receiving a real exposure notification, and ensures that the button is visible in the builds that will go to testflight
=> Add local push to simulate exposure EN debug button.

src/AffectedUserFlow/hmac.spec.ts, src/AffectedUserFlow/hmac.ts
Why:
----
The sorting algorithm for the list of exposure keys used to calculate the hmac should be lexicographical, meaning, numbers, symbols, capitals, and lowercase. Also, the keys from the native side are sent in base64 encoding so there's no need to re-encode them.
The [specification] says the hmac calculation on exposure keys should have the base64 encoded key, then the rolling start, then the rolling period, and finally the transmission risk joined by a `.`
This Commit:
----
- Removes the encoding logic for the TEKeys
- Sorts the list of exposure keys with the default sort algorithm
- Change the order of the exposure key serialization to put the `rollingStartNumber` first and the `rollingPeriod` after
[specification]: https://developers.google.com/android/exposure-notifications/verif …
=> Fix exposure keys serialization

android/app/src/main/java/org/pathcheck/covidsafepaths/exposurenotifications/DeviceInfoModule.java
`BluetoothAdapter.getDefaultAdapter()` returns null is bluetooth is not supported on the hardware, I think it will only happen on emulators.
This PR adds a null check to avoid having a NullPointerException in that case
=> (Android) Fix NPE on emulators

src/Activation/ActivateProximityTracing.tsx, src/locales/en.json, src/navigation/ActivationStack.tsx
Why?
------
Android does not need to ask for permission to send notifications like iOS does.
This commit
------
Remove the NotificationPermissions Activation screen from the onboarding flow for android.
[Trello](https://trello.com/c/OKLv4PdV/297-remove-screen-to-enable-notifications-on-android)
On Android, walk through onboarding flow and confirm that the notification permissions screen is no longer present.
On iOS, walk through onboarding flow and confirm that nothing has changed.
=> Hide NotificationPermissions Activation Screen on android

ios/BT/API/Model/KeySubmissionResponse.swift, ios/BT/API/Model/UserState.swift, ios/BT/API/Requests/DiagnosisKeyRequests.swift, ios/BT/ExposureManager.swift, ios/BT/Extensions/Foundation/Notification+Extensions.swift, ios/BT/Extensions/Foundation/String+Extensions.swift, ios/BT/Storage/BTSecureStorage.swift, ios/COVIDSafePaths.xcodeproj/project.pbxproj
Currently the `exposureKeyModule.postDiagnosisKeys` method submits the exposure keys to the exposure notifications server but it is not adding the revisionToken on the request. This token will be returned from the exposure notification server once the new keys are submitted and it has to be used on subsequent updates of the exposure keys.
This PR saves the `revisionToken` in Realm and uses it in subsequent requests
https://trello.com/c/ogfTrV4b/333-when-the-post-diagnosis-keys-process-ends-and-th-user-shares-the-keys-with-the-exposures-server-we-need-to-store-a-revision-toke
Verify that `revisionToken` is not sent in the first request and it's added in subsequent requests.
=> Add revision token to key submission request (iOS)

src/Home/Home.spec.tsx
Why:
----
Some of the tests on the Home spec are showing warnings about act.
This Commit:
----
- Remove some of the async nesting on waitFor blocks
- Mock the useApplicationInfo hook on the home tests
=> Fix Home tests warnings

src/Onboarding/OnboardingScreen.tsx, src/navigation/OnboardingStack.tsx
Why:
----
The number of onboarding screens defined on the onboarding stack is causing a require cycle.
This Commit:
----
- Move the `NUMBER_OF_ONBOARDING_SCREENS` constant closer to where it is used
=> Move constant closer to its use to avoid cycle

android/app/src/main/java/covidsafepaths/bt/exposurenotifications/network/DiagnosisKeyUploader.java, android/app/src/main/java/covidsafepaths/bt/exposurenotifications/storage/ExposureNotificationSharedPreferences.java, android/app/src/main/java/covidsafepaths/bt/exposurenotifications/storage/KeyValues.kt, android/app/src/main/java/covidsafepaths/bt/exposurenotifications/storage/Migration.kt, android/app/src/main/java/covidsafepaths/bt/exposurenotifications/storage/RealmSecureStorageBte.kt
Currently the `exposureKeyModule.postDiagnosisKeys` method submits the exposure keys to the exposure notifications server but it is not adding the revisionToken on the request. This token will be returned from the exposure notification server once the new keys are submitted and it has to be used on subsequent updates of the exposure keys.
This PR saves the `revisionToken` in a shared preference and uses it in subsequent requests
https://trello.com/c/ogfTrV4b/333-when-the-post-diagnosis-keys-process-ends-and-th-user-shares-the-keys-with-the-exposures-server-we-need-to-store-a-revision-toke
Verify that `verifyToken` is not sent in the first request and it's added in subsequent requests.
=> (Android) Add revisionToken to submit keys requests

src/Home/Home.spec.tsx, src/Home/Home.tsx, src/Home/useBluetoothStatus.ts, src/gaen/nativeModule.ts
Why:
As a user, who has been prompted to enable bluetooth, I want to see my
new bluetooth status reflected in the home screen so that I know it is
working.
This commit:
Introduces the AppState listener from react native. When an iOS user
foregrounds the app (in order to activate bluetooth in their settings),
or an Android user focuses the app (in order to either activate their
bluetooth settings, or use the notification menu to toggle bluetooth),
the app will now refetch the bluetooth status and set it into state.
This also fixes a bug I experienced where the status was not being
properly set on Android, because `isBluetoothEnabled` returned a
boolean, and we were checking if `status === 'true'`
Fixes [Trello](https://trello.com/c/ZPXtZnvi/320-when-i-do-not-have-bluetooth-enabled-and-the-a …
=> Update Bluetooth status on home screen on toggle

ios/COVIDSafePaths.xcodeproj/project.pbxproj
We'd like to sign release builds with the correct signing identity
This commit updates the signing identity for the release configuration
=> Correct Signing for Release Builds

src/More/ExposureListDebugScreen.spec.tsx, src/More/ExposureListDebugScreen.tsx, src/exposure.ts, src/factories/exposureDatum.tsx, src/gaen/dataConverter.spec.ts, src/gaen/dataConverters.ts
Why:
As a tester, I want to be clearly told when there are no exposures to
view in the debug menu, so that I know that it is working as expected.
This commit:
Adds empty state text to alert a debug menu user that when the device
has no current exposures. It also adds a test for this screen, and
refactors the debug screen to use the exposure information that we are
already storing in app context instead of re-fetching them.
Fixes: [Trello](uhttps://trello.com/c/fQzc2wFR/298-as-a-tester-when-i-go-to-the-show-exposures-debug-screen-and-there-are-no-exposures-i-see-some-no-exposures-indicatorrl)
- Open the app and clear exposures
- visit the "See exposures" screen
- Expect to see "no exposures" text
- Simulate exposure
- Return to the "See exposures" screen
- Expect to see the new simulated …
=> Add empty state text to exposure list debug screen

android/app/build.gradle
These dependencies where added by GPS, but we don't need them for GAEN.
Removing `org.bouncycastle:bcprov-jdk15on` also fixes some usages of `Random()` instead of `SecureRandom()` that were reported by ImmuniWeb
=> (Android) Remove unused dependencies

android/app/src/debug/AndroidManifest.xml, android/app/src/main/AndroidManifest.xml
`MainActivity` doesn't need to be called from external applications so it shouldn't be exported. This has been detected in the ImmuniWeb scan report.
I'm also moving `com.facebook.react.devsupport.DevSettingsActivity` to debug `AndroidManifest`.
=> (Android) Do not export MainActivity

bin/configure_builds.sh, ios/BT/Info.plist
Update configure_build script to update iOS info.plist with required ENDeveloperRegion and ENAPIVersion as required by apple
https://trello.com/c/9eW8zgpi/326-ios-endeveloperregion-enapiversion-for-infoplist
run ./bin/set_ha.sh and set a HA and check that the Info.plist is proplerly updated
=> add update for iOS configuration in configure_builds script

android/app/proguard-rules.pro, android/build.gradle, ios/Podfile.lock, package.json, yarn.lock
`react-native-background-fetch` dependency is not being used and it adds some exposed Android receivers that we don't need.
That issue has been reported by ImmuniWeb scan
=> Remove react-native-background-fetch

src/Home/useBluetoothStatus.ts, src/gaen/nativeModule.ts
Why:
There is currently a bug where toggling the BT status on android is not
reflected in the home screen, blocking people from using app features.
This commit:
Fixes an issue where we were not `await`-ing the promise resolution from
the native module.
Fixes: [Trello](https://trello.com/c/dcZu4wmf/338-android-bluetooth-cant-be-enabled)
- Test that toggling the bluetooth state on both Android and Bluetooth is reflected on the home screen
- Please note that BT must be successfully enabled (it may take a second or so) before switching back to the app in order to successfully be reflected
=> Fix bug where BT can't enable on android

android/app/src/main/java/org/pathcheck/covidsafepaths/exposurenotifications/DeviceInfoModule.java, android/app/src/main/java/org/pathcheck/covidsafepaths/exposurenotifications/ExposureNotificationClientWrapper.java
New method `exposureNotificationClient.deviceSupportsLocationlessScanning()` has been added in API v1.6 to check if the device needs to have Location enabled to use Exposure Notification.
This PR exposes it to the JS layer
https://trello.com/c/EOccYNcG/354-on-gaen-v16-sdk-on-android-if-locationless-mode-is-not-available-and-location-is-not-enabled-on-the-device-show-on-the-main-scre
=> (Android) Expose method to check if device supports locationless scanning

example.env.bt, src/Home/Home.tsx
Why?
------
When sharing the app, send the user to the app store to download the app - HA dependent.
[Trello](https://trello.com/c/YVm6ejAI/312-when-i-press-the-share-link-on-the-home-screen-i-would-like-to-get-the-actual-store-link-for-the-application)
[Pathcheck Mobile Resource PR](https://github.com/Path-Check/pathcheck-mobile-resources/pull/11)
=> Use the app or play store link for sharing the app

ios/Podfile.lock, src/Onboarding/ProtectPrivacy.tsx, src/Onboarding/Welcome.tsx
Why:
----
We have an IN_APP_NAME variable that will not be necessary, the app name should be uniform. For more context, the welcome message will become its own configuration and the IN_APP_NAME on the privacy part will be removed. This goes with a [PR] on the resources repo
This Commit:
----
- Removes usage of the IN_APP_NAME environment variable
[PR]: https://github.com/Path-Check/pathcheck-mobile-resources/pull/13
=> Use the application name consistently

src/Activation/AcceptEula.tsx, src/Onboarding/ValueProposition.tsx, src/navigation/ActivationStack.tsx
Why:
We would like to suppress the EULA for now until the product
requirements for it can be fully defined.
This commit:
Refactors the activation stack and removes the eula screen. We kept the
eula component in the repo as we expect to be reintroducing it in an
upcoming iteration.
=> Remove eula from activation stack

src/components/Button.tsx, src/styles/colors.ts
Why:
The current app does not implement the proper gradients for buttons as per the design files. To keep consistency within the code base, gradient variables were added into the color styles file. 
This commit:
- Adds gradient variables within the color styles
- Fixes two color declarations that were incorrect
=> Create and implement gradient variables

android/fastlane/Fastfile, ios/fastlane/Fastfile
QA team is not getting new builds because the group is not added as a destination in each release.
This PR allows us to configure the `destinations` array from Bitrise
=> Send AppCenter destinations as a parameter

src/AffectedUserFlow/CodeInput/CodeInputScreen.spec.tsx, src/AffectedUserFlow/CodeInput/CodeInputScreen.tsx, src/Home/Home.spec.tsx, src/Home/Home.tsx, src/PermissionsContext.tsx, src/gaen/nativeModule.ts
Why: prior to this commit, the PermissionsContext was exposing the `ENPermissionStatus` directly, which has a type of `[ENAuthorization, ENEnablement]`, which in turn have types:
```
type ENAuthorization = `UNAUTHORIZED` | `AUTHORIZED`
type ENEnablement = `DISABLED` | `ENABLED`
```
This resulted in complexity at the view layer because we had to import various types from the `PermissionsContext` and, for example, check to see if the `ENAuthorization === "AUTHORIZED"` or `ENEnablement === "DISABLED"`.
This commit instead exposes an `ENAuthorizationEnablementStatus`, of type `{ authorization: boolean, enablement: boolean }`.
The result of this is that we can check if exposure notifications are authorized with `exposureNotifications.status.authorization`, or if they are enabled with …
=> Refactor PermissionsContext

android/app/src/main/java/org/pathcheck/covidsafepaths/exposurenotifications/ExposureKeyModule.java, ios/BT/Storage/KeychainService.swift, ios/BT/bridge/ExposureKeyModule.m, src/gaen/nativeModule.ts
We'd like to move the key submission request to the JS layer and only use the native layer for revision token storage.
This commit adds native methods to store and fetch the revision token
=> Native Module to Store and Fetch Revision Token

src/ErrorScreen.tsx, src/ExposureHistory/ExposureDetail.tsx, src/More/ENLocalDiagnosisKeyScreen.tsx, src/More/ExposureListDebugScreen.tsx, src/SelfAssessment/Agreement.tsx, src/styles/forms.ts, src/styles/typography.ts
Why: prior to this commit, some of our smallest text sizes were too small.
This commit updates our text sizes so that the smallest fonts are still easy to read at
base accessibility settings.
Co-Authored-By: Alex Chen <achen178@gmail.com>
=> Update font sizes for general legibility and accessibility

App.tsx, __mocks__/@bugsnag/react-native.js, android/app/build.gradle, android/app/src/main/AndroidManifest.xml, android/app/src/main/java/org/pathcheck/covidsafepaths/MainApplication.java, ios/AppDelegate.m, ios/BT/Info.plist, ios/Podfile.lock, package.json, src/AffectedUserFlow/CodeInput/CodeInputForm.spec.tsx, src/AffectedUserFlow/CodeInput/CodeInputForm.tsx, src/AffectedUserFlow/PublishConsent/PublishConsentForm.spec.tsx, src/AffectedUserFlow/PublishConsent/PublishConsentForm.tsx, src/AffectedUserFlow/PublishConsent/PublishConsentScreen.spec.tsx, src/AffectedUserFlow/hmac.spec.ts, src/AffectedUserFlow/hmac.ts, src/logger.ts, yarn.lock
Why:
----
We are lacking visibility on the data flow during the submission of exposure keys. We need a way to gain insight on what are the errors, on which environment and what are the problems we are having. Namely which exchange is happening among all actors in the process:
- OS and application with keys
- Verification server and application
- Exposure Keys server and application
How:
----
By adding a logs service like `bugsnag` we not only have the ability to log the data flow among all the actors but also gain info on how the users are behaving and what other errors we might be missing.
This Commit:
----
- Install and setup `bugsnag`
- Add `Logger` service object to add relevant metadata to the session and send errors
- Add logs to the submission process and fix tests
Caveat:
---- …
=> Add bugsnag and logs to the key submission process

android/app/build.gradle, bin/dev_setup.sh, bin/fetch_ha_env.sh, ios/COVIDSafePaths.xcodeproj/xcshareddata/xcschemes/BT_Adhoc.xcscheme, ios/COVIDSafePaths.xcodeproj/xcshareddata/xcschemes/BT_Production.xcscheme, ios/COVIDSafePaths.xcodeproj/xcshareddata/xcschemes/BT_Staging.xcscheme, src/More/Menu.tsx
We'd like to suppress the debug menu for release builds, and also ensure that builds are not pointed to the release environment during testing
This commit introduces a `STAGING` env configuration that suppresses the debug menu and points to the dev server, as well as an `Adhoc` scheme for `iOS` that uses the `.env.bt` configuration
=> Introduce staging configuration

src/AffectedUserFlow/Start.tsx
Why: prior to this commit, the button at the bottom of the screen was not accessible at large accessibility text sizes.
=> Add ScrollView to AffectedUserFlow/Start

android/app/src/main/java/org/pathcheck/covidsafepaths/MainApplication.java
This PR disables Bugsnag on release builds.
Bugsnag has the concept of "stages" to identify each environment. We will only notify Bugsnag when using the `development` stage.
https://docs.bugsnag.com/platforms/android/configuration-options/#releasestage
https://docs.bugsnag.com/platforms/android/configuration-options/#enabledreleasestages
I think this is enough to disable it and nothing else is needed on the JS side: 
https://docs.bugsnag.com/platforms/react-native/react-native/#further-configuration.
If Bugsnag is enabled you will see logs like these:
```
2020-08-24 14:53:24.731 5831-6061/org.pathcheck.covidsafepaths.bt D/Bugsnag: Received NDK message com.bugsnag.android.StateEvent$StartSession@3d68367
2020-08-24 14:53:30.730 5831-5831/org.pathcheck.covidsafepaths.bt D/Bugsnag: Received …
```
=> (Android) Disable bugsnag on release builds

src/Onboarding/Welcome.tsx, src/components/Button.tsx, src/components/GradientBackground.tsx, src/components/index.ts, src/styles/layout.ts
This commit:
- Adds a `GradientBackground` component
- Uses `GradientBackground` on the Welcome screen
- Uses `useAngle` wherever we use `LinearGradient` currently
=> Add LinearGradient background to Welcome screen

App.tsx, src/AffectedUserFlow/PublishConsent/PublishConsentScreen.tsx, src/ConfigurationContext.tsx, src/ExposureHistory/ExposureDetail.spec.tsx, src/ExposureHistory/ExposureDetail.tsx, src/ExposureHistory/History/NoExposures.spec.tsx, src/ExposureHistory/History/NoExposures.tsx, src/Home/Home.spec.tsx, src/Home/Home.tsx, src/More/About.spec.tsx, src/More/About.tsx, src/More/Legal.spec.tsx, src/More/Legal.tsx, src/SelfAssessment/endScreens/Share.spec.tsx, src/SelfAssessment/endScreens/Share.tsx, src/factories/configurationContext.ts, src/factories/index.ts, src/navigation/MainTabNavigator.tsx
Why:
----
The configuration logic needs several safeguards on the way it is being used across the application, from defensive programming to decisions on how to consume it. Some of the operations are changing rapidly and it is hard to keep up. Also, the `react-native-config` package is very hard to test properly. To sum up:
We need a way to abstract the way we get configuration items for the application. This will be an item subject to changes in the next iterations. A few problems we are facing:
- The complexity of "interpreting" environment is scattered across the codebase
- Some logic is leaking from the environment into the business logic
- If any environment variable triggered a change in behavior testing that becomes cumbersome
- Lack of types from environment variables, everything …
=> Add configuration context

android/app/src/main/java/org/pathcheck/covidsafepaths/exposurenotifications/reactmodules/DebugMenuModule.java
This PR shows an exposure notification when `Simulate Exposure` is pressed in the debug menu.
It makes easier to test how the notification icon looks and it won't have any impact in the current flow (it doesn't insert anything in the database)
=> (Android) Show notification when Simulate Exposure is pressed

src/gaen/nativeModule.ts
To accurately reflect EN permissions state on app launch
This commit fixes a function signature mismatch between `PermissionsContext` and `nativeModule`
=> Function Signature Mismatch Fix

bin/download_assets.sh
Why:
----
We need to update the icons for each one of the builds corresponding to a different jurisdiction.
Caveat:
----
This process has only been tested locally and is still to test on the CI environment. Also there is currently only on jurisdiction with the assets available.
This Commit:
----
- Add a script to download assets from resources repo and copy to locations inside ios/android projects
Co-authored-by: John Schoeman <johnschoeman1617@gmail.com>
=> Add Script to get icon assets resources repo

src/AffectedUserFlow/CodeInput/CodeInputForm.spec.tsx, src/AffectedUserFlow/CodeInput/CodeInputForm.tsx, src/locales/en.json
Validate that the AffectedUser CodeInput is a number.
[Trello](https://trello.com/c/mPffXwd3/379-as-a-user-when-i-enter-a-verification-code-if-that-code-is-not-formated-correctly-only-digits-i-am-told-that-theres-a-formating)
=> Add a validation to AffectedUser CodeInput form

src/ConfigurationContext.tsx, src/Home/Home.tsx
Why:
Currently we are making a distinction between ios and android share
links, which doesnt meet the feature requirements as we do not know the
device of the user in which the app is being shared.
This commit:
Removes the casing on the device platform for the share app link and
replaces the two links in the env file with a single 'SHARE_APP_LINK'
Co-Authored-By: Arthur Gibson <arthur.gibson@pathcheck.org>
=> Use single share app link

android/app/build.gradle, android/fastlane/Fastfile, android/fastlane/README.md
We were using release signing configuration for staging, but it just slows down the process.
This PR uses debug signing configuration and adds a new fastlane command to make staging APKs
=> Use debug signing configuration for staging

ios/BT/Extensions/Foundation/String+Extensions.swift, ios/BT/Storage/KeychainService.swift
This commit removes unused code that made a distinction between environments when storing the revision token. Now that we store the revision token based on the key server url being used, that distinction is implicit.
=> Clean up keychain service.

src/More/ENDebugMenu.tsx, src/More/Menu.tsx
Why:
Currently we are only showing a portion of debug options on staging
builds and we would like to show them all.
This commit:
Removes the `__DEV__` check in the debug menu and updates the conditional
for showing the link to the debug menu to allow it for either staging or
`__DEV__` environments.
=> Show all debug options on staging builds

__mocks__/react-native-linear-gradient.js, src/Onboarding/Welcome.tsx, src/components/GradientBackground.tsx
Why: we previously weren't able to wrap large portions of View code in `LinearGradient` because it prevented our tests from working.
This commit:
- Mocks `LinearGradient` so it just acts as a `View` in tests
- Updates `GradientBackground` to take children
- Uses `GradientBackground` with children on `Welcome`
=> Refactor GradientBackground usage

android/app/src/main/java/org/pathcheck/covidsafepaths/exposurenotifications/ExposureNotificationClientWrapper.java, android/app/src/main/java/org/pathcheck/covidsafepaths/exposurenotifications/nearby/ExposureNotificationBroadcastReceiver.java, android/app/src/main/java/org/pathcheck/covidsafepaths/exposurenotifications/nearby/ProvideDiagnosisKeysWorker.java
This PR lowers the pull interval to 12 hours to avoid having to wait too much time to get an exposure notification.
https://trello.com/c/TE9xVKd1/451-pull-keys-2x-per-day
Check that the time shown in Exposure History screen is updated every 12 hours.
=> Pull exposure keys every 12 hours

src/AffectedUserFlow/PublishConsent/PublishConsentForm.spec.tsx, src/AffectedUserFlow/PublishConsent/PublishConsentForm.tsx, src/AffectedUserFlow/exposureNotificationAPI.spec.ts, src/AffectedUserFlow/exposureNotificationAPI.ts, src/locales/en.json
Why:
----
When the server returns a response stating that the keys sent were already inserted but no revision token was sent, we are displaying a scary and hard to understand error. This operation should not be treated as an error since the keys were added and therefore the exposed devices were notified and it should happen only if a positive was reported with a different jurisdiction. There is a disproportion of occurrences of it given the nature of how we test.
This Commit:
----
- Modify request management to handle no-op responses
- Add some copy to the error for the no-op response to the users
=> Update response handling for keys posting

src/ExposureContext.tsx, src/factories/exposureContext.tsx, src/factories/gaenStrategy.tsx, src/gaen/index.ts
Exposures stored in the native database were not visible in the UI after force quitting and re-opening the app
This commit accommodates the function signature `getCurrentExposures = async (): Promise<ExposureInfo>` in `nativeModule.ts` (had previously used a callback some weeks ago, the JS-layer functions calling the method were still using the callback although it had been changed) and also fetches exposures from the database on AppState change.
=> Fix for Exposure History Screen State Bug

android/app/src/main/java/org/pathcheck/covidsafepaths/exposurenotifications/ExposureNotificationClientWrapper.java, android/app/src/main/java/org/pathcheck/covidsafepaths/exposurenotifications/dto/RNExposureInformation.java, android/app/src/main/java/org/pathcheck/covidsafepaths/exposurenotifications/nearby/DiagnosisKeyFileSubmitter.java, android/app/src/main/java/org/pathcheck/covidsafepaths/exposurenotifications/nearby/ExposureConfigurations.kt, android/app/src/main/java/org/pathcheck/covidsafepaths/exposurenotifications/nearby/ExposureNotificationBroadcastReceiver.java, android/app/src/main/java/org/pathcheck/covidsafepaths/exposurenotifications/nearby/StateUpdatedWorker.java, android/app/src/main/java/org/pathcheck/covidsafepaths/exposurenotifications/network/Uris.java, android/app/src/main/java/org/pathcheck/covidsafepaths/exposurenotifications/reactmodules/DeviceInfoModule.java, android/app/src/main/java/org/pathcheck/covidsafepaths/exposurenotifications/reactmodules/ExposureHistoryModule.java, android/app/src/main/java/org/pathcheck/covidsafepaths/exposurenotifications/reactmodules/ExposureNotificationsModule.java, android/app/src/main/java/org/pathcheck/covidsafepaths/exposurenotifications/storage/ExposureNotificationSharedPreferences.java, android/app/src/main/java/org/pathcheck/covidsafepaths/exposurenotifications/storage/RealmSecureStorageBte.kt
This PR implements scoring on the client side .
It does fetch the EN configuration from the server and passes it to GAEN API to do the scoring.
Configuration is re-fetched every time we pull keys to get the latest changes (if any). If an error happens during the process we will use the previous configuration or the default one (check `ExposureConfigurations` constants) if it's the first time.
`setDiagnosisKeysDataMapping`  can only be called once within 7 days and it will throw `FAILED_RATE_LIMITED` if called twice, so there are some values that can only be changed once a week.
`getExposureWindows` has been replaced by `getDailySummaries` to provide a configuration object. We will trigger a notification only when `summary.getSummaryData().getWeightedDurationSum() >= …
=> (Android) Fetch configuration from server

src/Home/index.tsx, src/locales/en.json
Why: prior to this commit, we were not informing the relevant users that
they need Location enabled in the home page subheader copy.
=> Fix homepage copy issue

src/AffectedUserFlow/PublishConsent/PublishConsentForm.spec.tsx, src/AffectedUserFlow/PublishConsent/PublishConsentForm.tsx, src/AffectedUserFlow/exposureNotificationAPI.spec.ts, src/AffectedUserFlow/exposureNotificationAPI.ts, src/AffectedUserFlow/fetchWithTimeout.spec.ts, src/AffectedUserFlow/fetchWithTimeout.ts, src/locales/en.json
Why:
----
The publish keys request sometimes can timeout, the request is hanging and it it failing to complete. We need a way to detect when the request took too long and show the failure to the user.
This Commit:
----
- Add the `fetchWithTimeout` utility
- Wrap the fetch on the `postDiagnosisKeys` with a timeout of 5 seconds
- Display proper timeout error message to users when the request times out
How to test:
----
Submit keys through the flow and it should work as usual, and if you can send a first-time request(takes at least a second) and disconnect your internet in the middle you should see a timeout error
=> Wrap fetch call for publish keys on a timeout

__mocks__/react-native-safe-area-context.js, src/ExposureHistory/History/index.spec.tsx, src/ExposureHistory/History/index.tsx, src/Home/index.spec.tsx, src/Home/index.tsx, src/components/StatusBar.tsx, src/components/index.ts, src/navigation/index.ts
Why: prior to this commit, there were places within the app where screen
content would overlap with status bar content.
Using `SafeAreaView` does not result in the correct UI or functionality because
it results in challenging and non-intuitive cross-platform behavior.
The cross-platform behavior is more intuitive and predictable using a
plain `View`, which wraps the `StatusBar` component from React Native.
This `View`'s height is set using `insets.top` (provided by the `useSafeAreaInsets`
hook from `react-native-safe-area-context`). The background color on this `View`
effectively becomes the status bar's background color.
Notes:
- This should be used on all screens without a header bar because all screens will
be scrollable to support large accessibility text sizes. Most screens will use …
=> Introduce StatusBar component

App.tsx, ios/AppDelegate.m, src/logger.ts
Why:
We would only log errors for staging and dev builds
=> Only log errors on staging and dev builds

__mocks__/react-native-safe-area-context.js, src/Activation/AcceptEula.tsx, src/AffectedUserFlow/CodeInput/CodeInputForm.tsx, src/AffectedUserFlow/CodeInput/EnableExposureNotifications.tsx, src/AffectedUserFlow/Complete.tsx, src/AffectedUserFlow/PublishConsent/PublishConsentForm.spec.tsx, src/AffectedUserFlow/PublishConsent/PublishConsentForm.tsx, src/AffectedUserFlow/PublishConsent/PublishConsentScreen.tsx, src/AffectedUserFlow/Start.tsx, src/ExposureHistory/ExposureDetail.tsx, src/ExposureHistory/History/index.tsx, src/ExposureHistory/MoreInfo.tsx, src/ExposureHistory/index.tsx, src/Home/index.tsx, src/More/ENDebugMenu.tsx, src/More/LanguageSelection.tsx, src/More/Menu.tsx, src/Onboarding/OnboardingScreen.tsx, src/Onboarding/ProtectPrivacy.tsx, src/Onboarding/Welcome.tsx, src/ReportIssue/ReportIssueForm.tsx, src/SelfAssessment/index.js, src/components/StatusBar.tsx, src/navigation/index.ts
Why: in order for the status bar to render correctly on all platforms, we need
to make use of both the `StatusBar` component from React Native as well
as a custom `useStatusBarEffect` hook.
This commit:
- Updates the `StatusBar` component
- Updates `useStatusBarEffect` to take a background color to render the
status bar correctly on Android
- Uses `StatusBar` in all the appropriate places
- Uses `useStatusBarEffect` in all the appropriate places
Notes:
- `useStatusBarEffect` is used to set the `barStyle` on both platforms
- `useStatusBarEffect` is used to set the status bar background color on
Android
- `StatusBar` is used to set the status bar background color on iOS
- `StatusBar` should not be used if a header exists on the screen via
React Navigation
- `StatusBar` should be used on any …
=> Fix status bar rendering issues

bin/download_copy.sh, bin/download_copy_methods.rb, bin/helpers.rb, bin/set_ha.sh, src/ExposureContext.tsx, src/More/About.tsx, src/More/Legal.tsx, src/Onboarding/Welcome.tsx, src/configuration/copy.json, src/configuration/useAuthorityCopy.ts, src/locales/en.json
Why:
----
There are three configurable options on the application that each authority will set up independently, those user-facing text bodies need to be localized and should follow the same language preference that the application is using. They need to live on the resources repo since they are private to each HA.
This Commit:
----
- Add the download copy script
- Add the helper to consume a key, and fetch it from the copy json
- Add default values to useAuthorityCopy
- Display content from authority copy on legal and about if present
- Change surrounding scrollview for legal and about screens
- Update download file script
- Include download_copy_methods on the set_ha script
Reviewers:
----
This approach assumes that the content of the copy file will be verified prior usage. Also assumes …
=> Add helper for displaying configurable copy per HA

src/navigation/MoreStack.tsx
Centers the more menu on Android
Fixes [GAEN-150](https://pathcheck.atlassian.net/jira/software/projects/GAEN/boards/33/?selectedIssue=GAEN-150)
iOS:
Android:
=> Center more menu title

src/SystemServicesContext.tsx
`doesDeviceSupportLocationlessScanning()` is not present in the iOS version of the native module and was the root cause of the warning. This is technically still an issue, but it doesn't matter as the iOS builds shouldn't be invoking the function at all.
Co-Authored-By: John Schoeman <johnschoeman1617@gmail.com>
=> Fix unresolved promise issue in SystemServicesContext

bin/set_ha.sh, src/AffectedUserFlow/PublishConsent/PublishConsentForm.spec.tsx, src/AffectedUserFlow/PublishConsent/PublishConsentForm.tsx, src/AffectedUserFlow/exposureNotificationAPI.spec.ts, src/AffectedUserFlow/exposureNotificationAPI.ts, src/AffectedUserFlow/fetchWithTimeout.ts, src/locales/en.json
Why:
----
Some responses from the post-diagnosis keys endpoint return with a retry HTTP status code. We should honor these and retry the request when necessary.
How:
----
A document was shared about which error values deemed a retry response. This was used to determine the responses, in the case of the post-diagnosis endpoint, only `internal_error` and the responses with redirect headers `429` and `503`
This Commit:
----
- Adds retry logic to postDiagnosisKeys request
- Add post keys error for an internal error message
Reviewers:
----
Not sure about the delay after getting the retry to be confirmed, there is an [header] in these requests according to the HTTP standard, could not see any of those on my testing perhaps is worth checking? 
[header]: …
=> Retry post diagnosis request when necessary

src/Activation/ActivateProximityTracing.tsx, src/Activation/NotificationPermissions.spec.tsx, src/AffectedUserFlow/CodeInput/CodeInputScreen.spec.tsx, src/Home/ProximityTracingActivationStatus.tsx, src/Home/index.spec.tsx, src/PermissionsContext.tsx, src/factories/gaenStrategy.tsx, src/locales/en.json, src/navigation/ActivationStack.tsx, src/navigation/MainNavigator.tsx
Prior to this commit, on iOS, if the user did not enable exposure notifications in the onboarding flow, there was no way for them to enable exposure notifications at all.
This state was possible because, in the onboarding flow, if the user did not enable exposure notifications, exposure notification permissions were _never requested in the native layer_. This put the app in a state where it was not possible for the user to _authorize_ exposure notifications in settings.
- Removes the "Enable Exposure Notifications" alert on the javascript layer because the native enable exposure notifications alert makes it redundant
- Makes it so exposure notification permissions are always requested when the user tries to fix an issue with proximity tracing not working. We need to do this because it is …
=> Enable user to activate proximity tracing from home screen

src/PermissionsContext.tsx, src/factories/gaenStrategy.tsx, src/gaen/nativeModule.ts
Why: prior to this commit, a warning showed on iOS when the promise was rejected when requesting exposure notification permissions.
This commit:
- Handles the promise rejection when requesting exposure notification permissions
- Updates the `requestAuthorization` method in the native module to return `Promise<void>` instead of 'Promise<string>`
=> Handle rejected promise on request exposure notification permissions

src/Activation/ActivateProximityTracing.tsx, src/Activation/ActivationSummary.tsx, src/Activation/NotificationPermissions.spec.tsx, src/AffectedUserFlow/CodeInput/CodeInputScreen.spec.tsx, src/AffectedUserFlow/CodeInput/CodeInputScreen.tsx, src/Home/ProximityTracingActivationStatus.tsx, src/Home/index.spec.tsx, src/Home/index.tsx, src/PermissionsContext.tsx, src/gaen/nativeModule.ts, src/locales/en.json
Prior to this commit, we were not ensuring the platform was iOS before showing an unauthorized alert on the home screen.
- Checks to see if the platform is iOS before showing an unauthorized alert.
- Updates the home screen spec to test this behavior
- Uses `isPlatformiOS()` to avoid having to mock `Platform`
=> Ensure platform is iOS before showing unauthorized alert

src/ExposureHistory/History/index.tsx, src/ExposureHistory/index.tsx, src/navigation/ExposureHistoryStack.tsx
Why: prior to this commit, we were using `navigation.addListener` to check if the Exposure History screen was focused and updating state to trigger a re-render.
This commit:
- Uses `useIsFocused()` to trigger a re-render of the Exposure History screen on focus
- Removes the call to `observeExposures()` on the Exposure History Stack because it doesn't seem to be doing anything at the moment, given that we are not rendering a badge on the exposure history tab icon
=> Refactor method of re-rendering Exposure History screen on focus

android/app/src/main/java/org/pathcheck/covidsafepaths/exposurenotifications/reactmodules/DeviceInfoModule.java
On Android version 8.1 or lower there is a setting to get the location from mobile networks instead of using GPS.
We were only checking if the GPS provider is enabled.
This PR uses `LocationManagerCompat` and it implements this logic:
```
return locationManager.isProviderEnabled(LocationManager.NETWORK_PROVIDER)
|| locationManager.isProviderEnabled(LocationManager.GPS_PROVIDER);
```
https://pathcheck.atlassian.net/browse/GAEN-238
=> Check GPS or network on devices running Android 8.1 or lower

src/ExposureContext.tsx, src/factories/exposureContext.tsx, src/navigation/MainTabNavigator.tsx
We have a lot of unused code in the `ExposureContext`, likely a result of half-finished features that got dropped when priorities changed.
Removes this unused code.
=> Remove unused code from ExposureContext

src/Activation/AcceptEula.spec.tsx, src/Activation/AcceptEula.tsx, src/Activation/AcceptTermsOfService.spec.tsx, src/Activation/AcceptTermsOfService.tsx, src/ConfigurationContext.tsx, src/Onboarding/OnboardingScreen.tsx, src/Onboarding/ValueProposition.tsx, src/factories/configurationContext.ts, src/navigation/ActivationStack.tsx, src/navigation/index.ts
Why:
----
The accept eula/accept terms screen on the activation stack has been removed from it. We need a way to display it based solely on the configuration variable DISPLAY_ACCEPT_TERMS_OF_SERVICE. Also the eula link is not getting any values to navigate to
This Commit:
----
- Add the configuration to the configuration context
- Point skip and get started from onboarding to `root` screen on
activation stack
- Determine to add or not accept terms of service screen to stack based
on configuration on the activation stack
- Consume eula url value from the configuration
- Show the eula link only if the eula url is available
Reviewers:
----
This depends of a PR on the resources repo. The `default` screen on the activation stack will always be the one on top of the list if the name is not the …
=> Add eula link on the activation screen

src/AffectedUserFlow/CodeInput/CodeInputForm.tsx, src/AffectedUserFlow/verificationAPI.ts, src/locales/en.json
When the user tries to submit a verification code and there is no internet connection we are showing the error "Try a different code".
This PR shows an error saying "There is no internet connection" when that happens.
https://pathcheck.atlassian.net/browse/GAEN-260
Disable WiFi and mobile data and try to submit a verification code
=> Show error when there is no internet connection

src/Home/BluetoothActivationStatus.tsx, src/Home/LocationActivationStatus.tsx, src/Home/index.spec.tsx
The dialog to enable Location already had a button to "Open settings".
This PR adds the button to the Bluetooth dialog.
**Note:**
I haven't changed the copy, we should confirm with Art which copy we should use for these type of dialogs.
https://pathcheck.atlassian.net/browse/GAEN-237
- Disable Bluetooth
- Tap on the Fix icon
- Tap on Open Settings
=> Add button to open settings in order to enable Bluetooth

android/app/src/main/java/org/pathcheck/covidsafepaths/exposurenotifications/storage/Migration.kt
The IDE shows a warning saying that referencial equality for Longs is deprecated.
This PR fixes it
=> Fix referencial equality warning

src/Onboarding/Welcome.tsx
Why:
----
On smaller phones the call to action on the welcome screen can not be tapped because the image and text push it out the screen. We need this button to be reachable by users when it is not reachable.
How:
----
Adding a scroll view container where the container can grow to its full height will allow users on smaller screens to scroll down as they need to.
This Commit:
----
- Add scroll view container to welcome screen
Reviewers:
----
Not sure this is a long term solution to some text size issues but it allows users to move past this step.
=> Add scrollview around welcome screen
