Path-Check/gaen-mobile

example.env
Small change fixing typo in example env
=> Fix typo in ACCESS_TOKEN

jest/config.js, jest/setupFile.js, package.json, src/declarations.d.ts, yarn.lock
Why:
react-native-pulse is no longer being used.
=> Remove unused dependency

README.md, android/app/build.gradle
Update setup instructions to allow devs to spin up quickly.
Start from a fresh instance of the repo locally, and follow the setup instructions.
=> Update Setup Instructions for Android

.github/workflows/build.yml, android/app/build.gradle, android/build.gradle, android/settings.gradle
Use updated dependencies. They have not been updated in awhile and I would rather get them updated now instead of right before release. I've let this hang for too long.
=> Update Android Dependencies

src/More/ENDebugMenu.tsx, src/Onboarding/EulaModal.spec.tsx, src/Onboarding/EulaModal.tsx, src/Onboarding/Welcome.tsx
=> Add loading indicator to EULA webview

android/app/src/bt/java/covidsafepaths/bt/exposurenotifications/DebugMenuModule.java, android/app/src/bt/java/covidsafepaths/bt/exposurenotifications/ExposureNotificationClientWrapper.java, android/app/src/bt/java/covidsafepaths/bt/exposurenotifications/ExposureNotificationsModule.java, android/app/src/bt/java/org/pathcheck/covidsafepaths/MainActivity.java
Add method to toggle exposure notifications on Android
Functionality already implemented on React Native & iOS
Go to the Dev Menu and tap on `Toggle Exposure Notifications` button
=> [Android] Toggle Exposure Notifications

src/More/ENSubmitDebugForm.tsx, src/SelfAssessment/Agreement.js, src/SelfAssessment/AssessmentStart.spec.tsx, src/SelfAssessment/AssessmentStart.tsx, src/SelfAssessment/EmergencyAssessment.js, src/SelfAssessment/InfoText.tsx, src/SelfAssessment/endScreens/AssessmentComplete.js, src/SelfAssessment/endScreens/Caregiver.js, src/SelfAssessment/endScreens/Distancing.js, src/SelfAssessment/endScreens/Emergency.js, src/SelfAssessment/endScreens/Isolate.js, src/SelfAssessment/endScreens/Share.js, src/SelfAssessment/index.js
This commit converts the `SelfAssessment/AssessmentStart` and
`SelfAssessment/InfoText` files to Typescript.
- Tests should pass
=> Convert AssessmentStart and InfoText to Typescript

src/SelfAssessment/Agreement.tsx, src/SelfAssessment/index.js
This commit converts `SelfAssessment/Agreement` to Typescript.
Tests should pass.
=> Convert SelfAssessment/Agreement to Typescript

android/app/src/bt/java/covidsafepaths/bt/exposurenotifications/network/DiagnosisKeyUploader.java
We should send to the server the `appId` from .env variables instead of the AndroidManifest one.
=> Take appPackageName from .env variables

src/ErrorScreen.tsx
=> Style error screen

android/app/src/bt/java/covidsafepaths/bt/exposurenotifications/DebugMenuModule.java, android/app/src/bt/java/covidsafepaths/bt/exposurenotifications/ExposureKeyModule.java, android/app/src/bt/java/org/pathcheck/covidsafepaths/MainActivity.java
We were not reporting errors to the UI, so the user could never know if the upload succeeded or not.
This PR uses the Promise that is sent as a parameter and calls `resolve` or `reject` accordingly.
=> Add promise to submiteExposureKeys

ios/BT/API/Model/ExposureConfiguration.swift
=> Update exposure configuration (iOS)

.gitignore, jest/config.js
Added coverage reports for informational purpose only.  
NA
Run "yarn test"
=> Enabled coverage reports

.github/workflows/build.yml, android/app/build.gradle, android/fastlane/Fastfile
Remove staging variant as it is no longer used.
=> Remove Staging Variant

android/app/src/bt/java/covidsafepaths/bt/exposurenotifications/DebugMenuModule.java, android/app/src/bt/java/covidsafepaths/bt/exposurenotifications/nearby/DiagnosisKeyFileSubmitter.java, android/app/src/bt/java/covidsafepaths/bt/exposurenotifications/network/Uris.java, android/app/src/bt/java/covidsafepaths/bt/exposurenotifications/storage/RealmSecureStorageBte.kt
- Save in Realm the last file name we processed and expose a function to get it from React Native (for debugging/testing purposes)
- Do not download the file again if it was already processed
- Remove 20 batches per day limit. According to documentation the limit is per call, and we only call the method once a day.
Open the debug menu and tap on "Show Last Processed File Path"
=> Save last processed file name

android/app/src/bt/java/covidsafepaths/bt/exposurenotifications/nearby/ExposureConfigurations.java
Updated configuration parameters to match iOS
https://github.com/Path-Check/gaen-mobile/blob/bb80a3e55eb325a8770b3c000acfb1867521e5c5/ios/BT/API/Model/ExposureConfiguration.swift
Documentation: https://developers.google.com/android/exposure-notifications/exposure-notifications-api#data-structures
In the future we will receive those parameters from the backend.
=> Change configuration parameters

.github/workflows/build.yml, .github/workflows/distribute.yml, .github/workflows/test.yml, .gitignore, README.md, android/Gemfile, android/app/build.gradle, android/fastlane/Fastfile, android/fastlane/Pluginfile, bin/fetch_ha_env.sh, bin/save_keystore.sh, bin/set_ha.sh, ios/Gemfile
Add a new workflow to automatically distribute Android builds on each commit to develop.
**Releases:**
https://appcenter.ms/orgs/PathCheck/apps/packcheck-bt-mn/distribute/releases/
**Passing builds:**
https://github.com/Path-Check/gaen-mobile/runs/941610921?check_suite_focus=true
=> (Android) Distribute MN builds via Bitrise & Fastlane

src/AffectedUserFlow/PublishConsent/PublishConsentForm.tsx, src/Onboarding/EulaModal.tsx, src/Onboarding/ExplanationScreen.tsx, src/SelfAssessment/AssessmentQuestion.js, src/SelfAssessment/AssessmentStart.tsx, src/SelfAssessment/endScreens/AssessmentComplete.js, src/SelfAssessment/endScreens/Caregiver.js, src/SelfAssessment/endScreens/Distancing.js, src/SelfAssessment/endScreens/Emergency.js, src/SelfAssessment/endScreens/Isolate.js, src/SelfAssessment/endScreens/Share.js, src/components/Button.tsx, src/styles/buttons.ts, src/styles/typography.ts
Why: our current implementation of the Button component is a bit hard to
understand.
This commit:
- Updates the Button component
- Implements the Button component in the EulaModal screen
=> Refactor button component

README.md
Update readme with handling of dot env error for Android builds.
=> Update Android Dev Section in Readme

src/AffectedUserFlow/CodeInput/CodeInputForm.spec.tsx, src/AffectedUserFlow/CodeInput/CodeInputForm.tsx, src/AffectedUserFlow/Complete.spec.tsx, src/AffectedUserFlow/Complete.tsx, src/AffectedUserFlow/PublishConsent/PublishConsentForm.spec.tsx, src/AffectedUserFlow/PublishConsent/PublishConsentForm.tsx, src/AffectedUserFlow/PublishConsent/PublishConsentScreen.spec.tsx, src/AffectedUserFlow/PublishConsent/PublishConsentScreen.tsx
Why: many screens were navigating back to the More screen instead of the
Home screen.
=> Navigate back to Home from Affected User flow

android/app/src/main/AndroidManifest.xml
Why: this change is recommended in the upgrade from RN 0.61.5 to 0.62.2.
=> Update Android Manifest

android/app/build.gradle
I introduced a syntax error in this PR https://github.com/Path-Check/gaen-mobile/pull/176 that didn't let us make release builds.
This PR fixes it
=> Fix build.gradle

android/app/src/main/java/covidsafepaths/bt/exposurenotifications/utils/Util.java
This isn't a high risk fix, but a security scan of PathCheck recommended it and it can't hurt.
https://pathcheck.atlassian.net/browse/GAEN-107
=> Use SecureRandom API for Random Number

src/More/Menu.tsx, src/components/Button.tsx, src/styles/buttons.ts, src/styles/colors.ts, src/styles/typography.ts
Why: our disabled button style has changed.
=> Update button style and fix style regressions

android/app/src/main/AndroidManifest.xml, android/app/src/main/res/values/strings.xml
We were always displaying the app name "PatchCheck BT" in the launcher.
This PR will show the `DISPLAY_NAME` that is defined in the env file.
Install the app and look at the text below the app icon in the launcher.
=> (Android) Update app name in launcher

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, android/app/src/main/java/covidsafepaths/bt/MainApplication.java, android/build.gradle
Upgrade Realm version to `7.0.1`. Changelog [here](https://github.com/realm/realm-java/blob/master/CHANGELOG.md)
Removed [Stetho](https://github.com/uPhyca/stetho-realm) since it doesn't support the latest Realm version and it seems it's no longer maintained.
=> (Android) Upgrade realm dependency

android/build.gradle
Realm released a new version yesterday that fixes an issue when upgrading the file format.
I haven't experienced that issue but it may be worth upgrading the version to avoid having random crashes in the future.
https://github.com/realm/realm-java/blob/master/CHANGELOG.md#7022020-08-14
=> (Android) Upgrade Realm to version 7.0.2

src/navigation/MainTabNavigator.tsx
Co-Authored-By: John Schoeman <johnschoeman1617@gmail.com>
=> Toggle Report an Issue screen based on environment

src/More/Menu.tsx, src/locales/en.json
=> Update More Menu styling

src/Onboarding/OnboardingScreen.tsx
The onboarding screen was not scrollable on smaller mobile devices so we made this fix.
=> Make onboarding scrollable

App.tsx, ios/AppDelegate.m
- Check for the env[DEV] before loading bugsnag
=> Only use Bugsnag on the DEV environment

src/Home/Home.tsx, src/Onboarding/OnboardingScreen.tsx, src/Onboarding/Welcome.tsx, src/styles/typography.ts
This commit:
- Updates the styling of the protect privacy button on the onboarding screens
- Updates the styling of the select language button on the onboarding screens and welcome screen
=> Update onboarding styling

ios/BT/ExposureManager.swift, ios/BT/Extensions/BGTaskScheduler+Extensions.swift, ios/BT/Extensions/Exposure Notifications/ENManager+Extensions.swift
=> Small syntax change.

ios/BT/DebugAction.swift, ios/BT/ExposureManager+Debug.swift, ios/BT/ExposureManager.swift, ios/BT/bridge/ExposureKeyModule.m, ios/COVIDSafePathsTests/ExposureManagerUnitTests.swift
Remove postDiagnosisKeys since its not longer used, this is now being done in RN
=> remove postDiagnosisKeys

App.tsx, src/Activation/NotificationPermissions.spec.tsx, src/OnboardingContext.tsx, src/PermissionsContext.tsx
Why: we would like to have better test coverage.
Co-Authored-By: Amanda Beiner <aebeiner@gmail.com>
=> Add spec for NotificationPermissions

android/app/src/main/res/values/styles.xml
Those attributes are being overridden in the JS side, I'm removing them to avoid confusion
=> (Android) Remove unused theme attributes

ios/Podfile.lock, src/Activation/AcceptEula.tsx, src/Home/ShareLink.tsx, src/Home/index.tsx, src/Onboarding/Welcome.tsx, src/PermissionsContext.tsx, src/components/GradientBackground.tsx, src/locales/en.json, src/styles/colors.ts, src/styles/iconography.ts
Why: we would like to have a simpler home screen design that requires less development overhead and looks great on all devices.
=> Simplify home screen design

ios/Podfile.lock, src/AffectedUserFlow/CodeInput/CodeInputForm.tsx
=> Fix android code input text not showing

android/fastlane/Fastfile, android/fastlane/README.md, bin/helpers.rb, ios/fastlane/Fastfile
This PR adds a link to the configuration used for each build in the release notes.
It also removes some fastlane commands we are no longer using.
=> Add link to configuration in release notes

src/AffectedUserFlow/CodeInput/CodeInputScreen.tsx, src/AffectedUserFlow/CodeInput/EnableExposureNotifications.tsx, src/AffectedUserFlow/Start.tsx, src/styles/spacing.ts
Why: some of our styling was inconsistent across screens that should have consistent styles.
=> Clean up styling on affected user flow

android/build.gradle
Android 11 has been released this week.
This PR targets the latest SDK.
None of the API changes affect this app.
[Migration guide](https://developer.android.com/about/versions/11/migration)
Tested on Pixel 2XL with Android 11
=> Target Android 11

android/build.gradle
Update Kotlin and Realm versions
=> (Android) Update dependencies
